name:                bhs
version:             0.1.0.0
github:              "ekojsalim/bhs"
license:             LICENSE
author:              "Eko Julianto Salim"
maintainer:          "eko@ekojs.com"
copyright:           "2021 Eko Julianto Salim"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ekojsalim/bhs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- haskeline
- mtl
- optparse-applicative
- parsec
- text
- transformers
- HTTP
- tasty
- tasty-golden
- hspec

ghc-options:
- -Werror
- -fno-warn-unused-do-bind
- -fno-warn-unused-binds
- -fno-warn-type-defaults
- -fno-warn-type-defaults
- -fno-warn-name-shadowing
- -fwarn-duplicate-exports
- -fwarn-dodgy-exports
- -fwarn-dodgy-imports
- -fwarn-incomplete-patterns
- -fwarn-incomplete-record-updates
- -fwarn-missing-fields
- -fwarn-missing-methods
- -fwarn-orphans
- -fwarn-overlapping-patterns
- -fwarn-unused-imports
- -fwarn-tabs
- -fwarn-unrecognised-pragmas

library:
  source-dirs: src

executables:
  bhs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bhs

tests:
  bhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bhs
